spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xukai0324/note/
          search-paths: source/config/src/main/resources/config
  application:
    name: config-server
server:
  port: 8000